data:
  root: data/detection
  train_images: data/detection/images/train
  val_images: data/detection/images/val
  train_labels: data/detection/labels/train
  val_labels: data/detection/labels/val
  class_names: [motorbike, car, bus, truck]
  speed_labels: data/detection/speeds.csv
  format: yolo  # or coco

model:
  architecture: yolo11s
  pretrained_weights: yolov11s.pt
  img_size: 1280
  batch_size: 16
  epochs: 100
  optimizer: sgd
  learning_rate: 0.002
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  augment:
    hsv: true
    mosaic: true
    mixup: false

tracking:
  tracker_config: ultralytics/cfg/trackers/botsort.yaml
  conf_threshold: 0.35
  iou_threshold: 0.45

logging:
  project_dir: outputs/detection
  experiment_name: yolov11s_finetune
