inputs:
  video_path: null
  output_dir: outputs/pipeline
  window_seconds: 30
  min_objects_per_window: 5

segmentation:
  checkpoint: outputs/segmentation/best.ckpt
  device: cuda
  threshold: 0.5
  smooth_kernel: 5

roi:
  dash_lengths_m: [1.0, 2.0]
  y_group_tolerance_px: 30
  min_component_area: 40
  aspect_ratio_range: [0.2, 5.0]

tracking:
  detector_weights: outputs/detection/yolov11s.pt
  tracker_config: ultralytics/cfg/trackers/botsort.yaml
  conf_threshold: 0.35
  iou_threshold: 0.4
  device: cuda

loss_thresholds:
  density: {A: 5, B: 10, C: 14, D: 24, E: 40}
  speed_two_wheel: {A: 40, B: 35, C: 30, D: 25, E: 20, F: 0}
  speed_four_wheel: {A: 45, B: 40, C: 35, D: 25, E: 15, F: 0}
  default_vehicle_length_m: 3.0

reporting:
  export_tracks: true
  export_json: true
  display: false
